"""Add SystemSettings

Revision ID: 573fa57d3e09
Revises: 229ec545e335
Create Date: 2026-06-27 19:10:13.062610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573fa57d3e09'
down_revision: Union[str, Sequence[str], None] = '229ec545e335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_assign', sa.Boolean(), nullable=False),
    sa.Column('smart_deduplication', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence_threshold', sa.Integer(), nullable=False),
    sa.Column('email_alerts', sa.Boolean(), nullable=False),
    sa.Column('sms_alerts', sa.Boolean(), nullable=False),
    sa.Column('require_2fa', sa.Boolean(), nullable=False),
    sa.Column('session_timeout', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
